"""create safety observations table

Revision ID: 0ccdde94d73d
Revises: a78cfbc49586
Create Date: 2026-08-15 20:22:06.817065

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ccdde94d73d"
down_revision: str | Sequence[str] | None = "a78cfbc49586"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "safety_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("inspection_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=True),
        sa.Column("location", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("immediate_action_taken", sa.Text(), nullable=True),
        sa.Column(
            "requires_corrective_action",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "category IN ("
                "'housekeeping', "
                "'ppe', "
                "'fall_protection', "
                "'electrical', "
                "'equipment', "
                "'excavation', "
                "'lifting_rigging', "
                "'environmental', "
                "'fire_prevention', "
                "'access_egress', "
                "'other'"
                ")"
            ),
            name="ck_safety_observations_category",
        ),
        sa.CheckConstraint(
            ("kind IN ('safe_practice', 'unsafe_condition', 'unsafe_behavior', 'near_miss')"),
            name="ck_safety_observations_kind",
        ),
        sa.CheckConstraint(
            ("severity IS NULL OR severity IN ('low', 'medium', 'high', 'critical')"),
            name="ck_safety_observations_severity",
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["inspection_id"], ["inspections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_safety_observations_inspection_id"),
        "safety_observations",
        ["inspection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_safety_observations_organization_id"),
        "safety_observations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_safety_observations_project_id"),
        "safety_observations",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_safety_observations_project_id"), table_name="safety_observations")
    op.drop_index(op.f("ix_safety_observations_organization_id"), table_name="safety_observations")
    op.drop_index(op.f("ix_safety_observations_inspection_id"), table_name="safety_observations")
    op.drop_table("safety_observations")
    # ### end Alembic commands ###
