"""create corrective actions table

Revision ID: 411057bc7701
Revises: 0ccdde94d73d
Create Date: 2026-08-16 21:09:48.565448

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "411057bc7701"
down_revision: str | Sequence[str] | None = "0ccdde94d73d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corrective_actions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("inspection_id", sa.Uuid(), nullable=False),
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="open", nullable=False),
        sa.Column("assigned_to_user_id", sa.Uuid(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("completion_notes", sa.Text(), nullable=True),
        sa.Column("completed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_notes", sa.Text(), nullable=True),
        sa.Column("verified_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "(status IN ('open', 'in_progress') AND "
                "completed_at IS NULL AND "
                "completed_by_user_id IS NULL AND "
                "completion_notes IS NULL AND "
                "verified_at IS NULL AND "
                "verified_by_user_id IS NULL) "
                "OR "
                "(status = 'completed' AND "
                "completed_at IS NOT NULL AND "
                "completed_by_user_id IS NOT NULL AND "
                "completion_notes IS NOT NULL AND "
                "verified_at IS NULL AND "
                "verified_by_user_id IS NULL) "
                "OR "
                "(status = 'verified' AND "
                "completed_at IS NOT NULL AND "
                "completed_by_user_id IS NOT NULL AND "
                "completion_notes IS NOT NULL AND "
                "verified_at IS NOT NULL AND "
                "verified_by_user_id IS NOT NULL)"
            ),
            name="ck_corrective_actions_workflow_state",
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'medium', 'high', 'critical')",
            name="ck_corrective_actions_priority",
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'completed', 'verified')",
            name="ck_corrective_actions_status",
        ),
        sa.ForeignKeyConstraint(["assigned_to_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["completed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["inspection_id"], ["inspections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["observation_id"], ["safety_observations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["verified_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_corrective_actions_assigned_to_user_id"),
        "corrective_actions",
        ["assigned_to_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_corrective_actions_inspection_id"),
        "corrective_actions",
        ["inspection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_corrective_actions_observation_id"),
        "corrective_actions",
        ["observation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_corrective_actions_organization_id"),
        "corrective_actions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_corrective_actions_project_id"), "corrective_actions", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_corrective_actions_project_id"), table_name="corrective_actions")
    op.drop_index(op.f("ix_corrective_actions_organization_id"), table_name="corrective_actions")
    op.drop_index(op.f("ix_corrective_actions_observation_id"), table_name="corrective_actions")
    op.drop_index(op.f("ix_corrective_actions_inspection_id"), table_name="corrective_actions")
    op.drop_index(
        op.f("ix_corrective_actions_assigned_to_user_id"), table_name="corrective_actions"
    )
    op.drop_table("corrective_actions")
    # ### end Alembic commands ###
