"""create inspections table

Revision ID: a78cfbc49586
Revises: 8bdc68335273
Create Date: 2026-08-14 22:45:35.875324

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a78cfbc49586"
down_revision: str | Sequence[str] | None = "8bdc68335273"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inspections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("inspection_type", sa.String(length=32), nullable=False),
        sa.Column("inspection_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("result", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("performed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            (
                "(status = 'draft' "
                "AND submitted_at IS NULL) "
                "OR (status = 'submitted' "
                "AND submitted_at IS NOT NULL "
                "AND result IS NOT NULL)"
            ),
            name="ck_inspections_submission_state",
        ),
        sa.CheckConstraint(
            (
                "inspection_type IN ("
                "'general_site', "
                "'daily_site', "
                "'weekly_site', "
                "'pre_task', "
                "'equipment', "
                "'electrical', "
                "'environmental', "
                "'other'"
                ")"
            ),
            name="ck_inspections_type",
        ),
        sa.CheckConstraint(
            ("result IS NULL OR result IN ('satisfactory', 'needs_attention', 'critical')"),
            name="ck_inspections_result",
        ),
        sa.CheckConstraint("status IN ('draft', 'submitted')", name="ck_inspections_status"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["performed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inspections_organization_id"), "inspections", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_inspections_project_id"), "inspections", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inspections_project_id"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_organization_id"), table_name="inspections")
    op.drop_table("inspections")
    # ### end Alembic commands ###
